// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webrtc;

namespace webrtc.Migrations
{
    [DbContext(typeof(RTCContext))]
    partial class RTCContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("webrtc.IceCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CandidateJson");

                    b.Property<int>("PeerId");

                    b.HasKey("Id");

                    b.HasIndex("PeerId");

                    b.ToTable("IceCandidates");
                });

            modelBuilder.Entity("webrtc.PeerDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Sdp");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("Peers");
                });

            modelBuilder.Entity("webrtc.IceCandidate", b =>
                {
                    b.HasOne("webrtc.PeerDescription", "Peer")
                        .WithMany("IceCandidates")
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
